// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPO6ABzsr7LemaxY-l8YdYhOZVzO9TeQI',
    appId: '1:340648294228:web:011acb7dc150ea369fbac1',
    messagingSenderId: '340648294228',
    projectId: 'device-streaming-70d2d53c',
    authDomain: 'device-streaming-70d2d53c.firebaseapp.com',
    storageBucket: 'device-streaming-70d2d53c.firebasestorage.app',
    databaseURL: 'https://device-streaming-70d2d53c-default-rtdb.europe-west1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPO6ABzsr7LemaxY-l8YdYhOZVzO9TeQI',
    appId: '1:340648294228:android:011acb7dc150ea369fbac1',
    messagingSenderId: '340648294228',
    projectId: 'device-streaming-70d2d53c',
    storageBucket: 'device-streaming-70d2d53c.firebasestorage.app',
    databaseURL: 'https://device-streaming-70d2d53c-default-rtdb.europe-west1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPO6ABzsr7LemaxY-l8YdYhOZVzO9TeQI',
    appId: '1:340648294228:ios:011acb7dc150ea369fbac1',
    messagingSenderId: '340648294228',
    projectId: 'device-streaming-70d2d53c',
    storageBucket: 'device-streaming-70d2d53c.firebasestorage.app',
    databaseURL: 'https://device-streaming-70d2d53c-default-rtdb.europe-west1.firebasedatabase.app',
    iosBundleId: 'com.biletsokagi.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPO6ABzsr7LemaxY-l8YdYhOZVzO9TeQI',
    appId: '1:340648294228:ios:011acb7dc150ea369fbac1',
    messagingSenderId: '340648294228',
    projectId: 'device-streaming-70d2d53c',
    storageBucket: 'device-streaming-70d2d53c.firebasestorage.app',
    databaseURL: 'https://device-streaming-70d2d53c-default-rtdb.europe-west1.firebasedatabase.app',
    iosBundleId: 'com.biletsokagi.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPO6ABzsr7LemaxY-l8YdYhOZVzO9TeQI',
    appId: '1:340648294228:web:011acb7dc150ea369fbac1',
    messagingSenderId: '340648294228',
    projectId: 'device-streaming-70d2d53c',
    authDomain: 'device-streaming-70d2d53c.firebaseapp.com',
    storageBucket: 'device-streaming-70d2d53c.firebasestorage.app',
    databaseURL: 'https://device-streaming-70d2d53c-default-rtdb.europe-west1.firebasedatabase.app',
  );
}